apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: face-reg-ingress
  namespace: face-reg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: face-reg.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
